# Header
menu:
  首页: /
  新闻: /archives
  项目: /projects
  友链: /links
  关于: /about

# Content
excerpt_link: 阅读全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /images/favicon.svg
webclip: /images/webclip
brand:   /images/brand.svg

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/banner/banner.jpg
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: 梦幻彼岸工作室
  secondary: 即使迷茫 也要前行
  archives: 汇聚热点话题 打造创新思路
  pages: 即使迷茫 也要前行 
  posts: 一旦舍弃了个性，就和死了没区别。

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js